FROM node:18-slim

# Update and install dependencies
RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get install -y --no-install-recommends wget gnupg ca-certificates apt-transport-https fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release xdg-utils

# Download and install Chrome
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
    dpkg -i google-chrome-stable_current_amd64.deb || apt-get -yf install && \
    rm google-chrome-stable_current_amd64.deb && \
    sed -i 's|HERE/chrome"|HERE/chrome" --no-sandbox|g' /opt/google/chrome/google-chrome

# Install Redis
RUN apt-get install -y redis-server && \
    service redis-server start && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/*

# Verify Node.js and npm versions
RUN node -v && npm -v

# Set PATH for Chrome
ENV CHROME_PATH=/usr/bin/google-chrome

# Run Redis in the background
CMD redis-server --daemonize yes && tail -f /dev/null