export const REPORT_HEADER = {
  ORDER_GENERAL: [
    'id',
    'restaurantName',
    'restaurantNameAr',
    'status',
    'createdAt',
    'orderType',
    'tableName',
    'tableNameAr',
    'paymentStatus',
    'paymentMethod',
    'couponCode',
    'totalOrderAmount',
    'refundAmount',
    'customerName',
    'customerEmail',
    'customerPhoneNumber',
  ],
  ORDER_USER: [
    'restaurantName',
    'restaurantNameAr',
    'customerName',
    'customerPhoneNumber',
    'orderType',
    'visitCount',
    'lastVisitDate',
  ],
  ORDER_LIVE_CYCLE: [
    'restaurantName',
    'restaurantNameAr',
    'status',
    'createdAt',
    'updatedAt',
    'orderId',
    'timeToOrder',
    'fromOrderToKitchen',
    'fromKitchenToOrderReady',
    'fromOrderReadyToClose',
    'fromScanToClose',
    'fromOrderToClose',
  ],
  RESERVATIONS: [
    'restaurantName',
    'restaurantNameAr',
    'customerName',
    'customerPhoneNumber',
    'isCancelled',
    'totalMembers',
    'date',
  ],
  ORDER_KITCHEN: [
    'chef',
    'status',
    'createdAt',
    'orderType',
    'orderId',
    'timeToStartPrepare',
    'timeFromPrepareToReady',
  ],
  PAYMENT_REFUND: [
    'cashierName',
    'orderId',
    'amount',
    'paymentMethod',
    'status',
    'createdAt',
  ],
  PAYMENT: [
    'cashierName',
    'transferNumber',
    'amount',
    'paymentMethod',
    'status',
    'createdAt',
  ],
  PAYOUT_PREVIEW: [
    'Date/Time',
    'Supplier ID',
    'Supplier Name',
    'Amount Received',
    'BANK ID',
    'Bank IBAN',
    'Bank Name',
    'Amonut to be Paid to Supplier',
    'Merchant Track ID',
    'Transaction ID',
    'Reference ID',
    'Our Transaction ID',
    'Scheduled Payout Date',
    'Payment Method',
    'Settlement Status',
  ],
  PAYOUT_AGGREGATED_PREVIEW: [
    'Supplier ID',
    'Supplier Name',
    'Amount Received',
    'BANK ID',
    'Bank IBAN',
    'Bank Name',
    'Amonut to be Paid to Supplier',
    'Scheduled Payout Date',
  ],
};
export const REPORT_FIELDS = {
  ORDER_GENERAL: [
    'id',
    'restaurantName',
    'restaurantNameAr',
    'status',
    'createdAt',
    'orderType',
    'tableName',
    'tableNameAr',
    'paymentStatus',
    'paymentMethod',
    'couponCode',
    'totalOrderAmount',
    'refundAmount',
    'customerName',
    'customerEmail',
    'customerPhoneNumber',
  ],
  ORDER_USER: [
    'restaurantName',
    'restaurantNameAr',
    'customerName',
    'customerPhoneNumber',
    'orderType',
    'visitCount',
    'lastVisitDate',
  ],
  ORDER_LIVE_CYCLE: [
    'restaurantName',
    'restaurantNameAr',
    'status',
    'createdAt',
    'updatedAt',
    'orderId',
    'timeToOrder',
    'fromOrderToKitchen',
    'fromKitchenToOrderReady',
    'fromOrderReadyToClose',
    'fromScanToClose',
    'fromOrderToClose',
  ],
  RESERVATIONS: [
    'restaurantName',
    'restaurantNameAr',
    'customerName',
    'customerPhoneNumber',
    'isCancelled',
    'totalMembers',
    'date',
  ],
  ORDER_KITCHEN: [
    'chef',
    'status',
    'createdAt',
    'orderType',
    'orderId',
    'timeToStartPrepare',
    'timeFromPrepareToReady',
  ],
  PAYMENT_REFUND: [
    'cashierName',
    'orderId',
    'amount',
    'paymentMethod',
    'status',
    'createdAt',
  ],
  PAYMENT: [
    'cashierName',
    'transferNumber',
    'amount',
    'paymentMethod',
    'status',
    'createdAt',
  ],
  PAYOUT_PREVIEW: [
    'date',
    'supplierId',
    'supplierName',
    'amountReceived',
    'bankId',
    'bankIban',
    'bankName',
    'amountTobePaid',
    'paymentId',
    'transactionId',
    'referenceId',
    'ourTransactionId',
    'scheduledPayoutDate',
    'paymentMethod',
    'settlementStatus',
  ],
  PAYOUT_AGGREGATED_PREVIEW: [
    'supplierId',
    'supplierName',
    'amountReceived',
    'bankId',
    'bankIban',
    'bankName',
    'amountTobePaid',
    'scheduledPayoutDate',
  ],
};

export const ONE_MINUTE = 60000;
