name: Docker kdsapi workflow

on:
  push:
    branches: [ "main" ] # Trigger on pushes to the main branch
  pull_request:
    branches: [ "main" ] # Optional: Trigger on pull requests to main

env:
  # Use your GitHub username for the IMAGE_OWNER
  IMAGE_OWNER: ${{ github.repository_owner }}
  # Name of your Docker image (e.g., your-react-app)
  IMAGE_NAME: kdsapi # <<< IMPORTANT: Changed to kdsapi based on your pull attempt

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required to write to GitHub Packages

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3 # Required for multi-platform builds

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3 # This action sets up Buildx, which is required for caching and multi-platform builds

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        # GITHUB_TOKEN is a special token provided by GitHub Actions
        # It has permissions to push to GitHub Packages for the current repository
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: . # Path to the Dockerfile (current directory)
        push: true # Push the image to the registry
        platforms: linux/amd64,linux/arm64/v8 # Build for both AMD64 and ARM64 architectures
        tags: |
          ghcr.io/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_NAME }}:latest
          ghcr.io/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        cache-from: type=gha # Use GitHub Actions cache for faster builds
        cache-to: type=gha,mode=max
